### ISSUE TITLE
[QUESTION]How Alpa ILP deal with the boundary instructions associated with another pipeline stage?

### ISSUE THREAD

**Issue by adamantboy** [alpa-projects/alpa#459]
I find that, there are pipeline marker instructions(start marker or end marker who transmit in out vars ) at a stage boundary，but how ILP deal with these instructions or how ILP calculate costs of instructions influenced by another pipeline stage? Hope for your reply.

**Comment by adamantboy** [comment]
@ZYHowell

**Comment by zhisbug** [comment]
Hi @adamantboy, thanks for your interest. ILP need not do anything with the pipeline markers as ILP works within a stage. Those markers are at stage boundary, and they are implemented as identity functions (hence no effect).

What do you mean by `costs of instructions influenced by another pipeline stage`? Could you give an example?

**Comment by adamantboy** [comment]
Thank you for your reply. For example, when the sharding strategy of A at ILP1 is changed, then the communication cost between A and B will be influenced.How ILP deal with the communication cost between A and B?
![image](https://user-images.githubusercontent.com/20296728/169248232-95f1ddd6-9006-4062-b45c-d5ff32c99c7a.jpg)

**Comment by zhisbug** [comment]
ILP does not model that; ILP only locally optimizes for a single stage parallel execution. 

The cross-stage communication you mentioned is called "cross mesh resharding" in Alpa. It is handled by the [cross mesh sharding pass](https://github.com/alpa-projects/alpa/blob/main/alpa/pipeline_parallel/cross_mesh_resharding.py) (corresponding to the "parallelism orchestration pass" in paper). You can go through the code, there are some optimization algorithms to minimize their communication.

**Comment by ZYHowell** [comment]
> there are some optimization algorithms to minimize their communication.

Based on the local-allgather optimization(https://github.com/alpa-projects/alpa/issues/350) or broadcast(https://github.com/alpa-projects/alpa/issues/416), the cross-mesh communication is exactly one replica, and the rest communication runs with high bandwidth allgather(or broadcast ring impl).

Currently, we do not consider the time of this communication in our stage construction algorithm, but it can be added easily: just use the tensor size to divide the cross node bandwidth, because as mentioned above, there is always exactly one replica.

**Comment by zhuohan123** [comment]
Close this issue because the question is answered. Please let us know if you have more questions. Also, welcome to join our [Slack](https://forms.gle/YEZTCrtZD6EAVNBQ7) to discuss more!
