### ISSUE TITLE
Question to the strategy length

### ISSUE THREAD

**Issue by kevinsouthxu** [alpa-projects/alpa#616]
Hi! I have a question about the number of parallelism strategies for every single operator. In my opinion, this number will become larger with more GPUs. However, I find that it is not true.
Specifically, I directly output the s_len at https://github.com/alpa-projects/alpa/blob/main/alpa/shard_parallel/auto_sharding.py#L676. Then I find that in an 8 GPU machine with mesh(1,8), the s_len is the same as that in a 4 GPU machine with mesh(1,4). I am wondering why the number of strategies for every single operator does not increase.

**Comment by merrymercy** [comment]
For logical mesh shape (1, 4) and logical mesh shape (1, 8), the number of strategies is the same, because the number of strategies depends on the number of non-zero dimensions of the logical mesh, but not the actual length of the dimension.

However, for 4 GPUs and 8 GPUs, 8GPUs does have more strategies. Because 8 GPUs can be casted into logical mesh (1, 8), (2, 4), (4, 2) or (8, 1), while 4GPUs can only be casted to (1, 4), (2, 2), (4, 1).
