### ISSUE TITLE
Using torchDynamo as pytorch FE?

### ISSUE THREAD

**Issue by Jack47** [alpa-projects/alpa#717]
**System information**
- Alpa version:
- Are you willing to contribute it (Yes/No):
Yes

**Describe the new feature and the current behavior/state**

Hi  Alpa team, Alpa is inspiring and interesting!

I want to try Alpa pytorch feature, currently Alpha use [torch.fx.symbolic_trace](https://github.com/alpa-projects/alpa/blob/main/alpa/torch/nn/__init__.py#L381) to get graph from pytorch models. symbolic_trace has some [limitations](https://pytorch.org/docs/stable/fx.html#limitations-of-symbolic-tracing), do you guys have plan to improve it by using torchDynamo(3rd-gen pytorch compiler FE)？

**Will this change the current API? How?**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhisbug** [comment]
@yf225

**Comment by yf225** [comment]
TorchDynamo mainly helps with generating multiple sub-graphs for a model, but Alpa currently only works with a single whole graph, so we can't really benefit from TorchDynamo at the moment.

The limitations of FX tracing actually exactly matches the limitations of Alpa (e.g. no data-dependent control flow, no non-JAX functions, that's why we choose FX tracing as the PyTorch graph export solution.

**Comment by Jack47** [comment]
> TorchDynamo mainly helps with generating multiple sub-graphs for a model, but Alpa currently only works with a single whole graph, so we can't really benefit from TorchDynamo at the moment.
> 
> The limitations of FX tracing actually exactly matches the limitations of Alpa (e.g. no data-dependent control flow, no non-JAX functions), that's why we choose FX tracing as the PyTorch graph export solution.

Thanks for reply @yf225 , where can I get the limitations of Alpa?

**Comment by yf225** [comment]
For "no data-dependent control flow" limitation, it's similar to `jax.jit`'s limitation: https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-jit, particularly please see "functions with argument-value dependent shapes" section.

For "no non-JAX functions" limitation, it's because JAX IR graph can only have JAX operators (i.e. XLA HLO IR), so e.g. calls to `numpy` will not work in the JAX IR graph.
