### ISSUE TITLE
Asking for support Powerpc machine

### ISSUE THREAD

**Issue by zfchenUnique** [alpa-projects/alpa#748]
**System information**
- Alpa version: latest
- Are you willing to contribute it (Yes/No): Yes

**Describe the new feature and the current behavior/state** 
I would like to know whether there will be support for PPC architectures.

**Will this change the current API? How?**
No.
**Describe alternatives you've considered**

**Additional context**
I have only access to the powerpc machines, which always shows I did not have correct version of ray. Is there possible to provide a setup guidance for PPC machines? Thanks in advance.

**Comment by zhuohan123** [comment]
We don't have access to PPC machines so it's hard for us to provide setup guidance. Theoretically, Alpa should work on PPC machines if the following dependencies work:
1. JAX/XLA. JAX is purely python so it should work on PPC. XLA is C++, but because [tensorflow works on PPC](https://github.com/tensorflow/build#community-supported-tensorflow-builds), I think XLA should also work on PPC.
2. ILP Solver. The one we are currently using is [CBC](https://github.com/coin-or/Cbc). I cannot immediately tell whether it works for PPC or not.
3. Ray. Ray [should be able to work with PPC](https://github.com/ray-project/ray/issues/2358) if you compile your own ray wheel.

**Comment by zhuohan123** [comment]
In addition, can you share the exact error message you get?

**Comment by merrymercy** [comment]
closed due to inactivity
