### ISSUE TITLE
[BUG] Convert 1.3-b opt model to consolidated pt error

### ISSUE THREAD

**Issue by zhanghaoie** [alpa-projects/alpa#832]
**Please describe the bug**

  0%|                                                                                                                                                                  | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "step_2_consolidate_992_shards_to_singleton.py", line 488, in <module>
    consolidate_fsdp_shards(args.read_prefix,
  File "step_2_consolidate_992_shards_to_singleton.py", line 156, in consolidate_fsdp_shards
    metadata.append(ckpt["shard_metadata"])
KeyError: 'shard_metadata'
no shard_metadata in ckpt file

**Comment by zhanghaoie** [comment]
face the problem when use step_2_consolidate_992_shards_to_singleton.py to convert opt model  https://github.com/facebookresearch/metaseq/tree/main/projects/OPT

**Comment by merrymercy** [comment]
For opt-1.3b, you don't need to do this manual conversion. Alpa will automatically download and convert weights from huggingface model hub

**Comment by zhanghaoie** [comment]
but I want to convert opt-IML model，which has no weights publicy available.

**Comment by merrymercy** [comment]
I see. I guess their weight format is slightly different. @zhisbug may know this issue better.

**Comment by zhisbug** [comment]
@zhanghaoie this script does not support opt-1.3b conversion. Opt-1.3B is a special case, because when Meta released its weight, it was the only one without metadata (while all other weights were with metadata). 

That's why the script does not work. 

Alternatively, you can download HF's opt-1.3b consolidated weight and write a simple script to parse the HF weight, save each weight tensor by its name on disk in NumPy format. That will do the same job. This should be easy to do because the 1.3B model can be loaded on most desktops.
